allowed_relations = [
    "Adjuvant pembrolizumab therapy for RCC is a topic of debate and uncertainty among clinicians.",
    "Awaiting overall survival (OS) data to draw definitive conclusions.",
    "Belzutifan is being evaluated in combination with other therapies like cabozantinib and lenvatinib.",
    "Belzutifan may have a potential role in the treatment sequence for renal cell carcinoma.",
    "Belzutifan shows promising efficacy and response rates in clinical trials for renal cell carcinoma.",
    "Biomarkers are needed for patient selection and treatment decision-making in RCC.",
    "Cabo monotherapy as a potential treatment option after Pembro adjuvant therapy.",
    "Cabo monotherapy as an effective treatment for specific cases.",
    "Cabo/Nivo combination therapy as a potential first-line treatment option.",
    "Cabozantinib dose reduction is common for better tolerance and maintenance.",
    "Cabozantinib has better tolerance and efficacy compared to lenvatinib.",
    "Cabozantinib is considered an effective TKI for treating RCC patients with bone and brain metastases.",
    "Cabozantinib is considered an effective TKI, but some HCPs prefer to use it as a second-line treatment due to its potential toxicity profile.",
    "Cabozantinib is effective in later lines after progression on other therapies.",
    "Cabozantinib plus nivolumab combination is preferred as first-line treatment for RCC patients with bone and brain metastases.",
    "Cabozantinib treatment duration varies in different settings.",
    "Capacity challenges and increasing workload due to new treatments.",
    "Challenges and limitations in accessing certain combination therapies.",
    "Clinicians are concerned about the impact of adjuvant therapy on treatment sequencing and capacity.",
    "Clinicians are gaining experience with combination therapies and toxicity management.",
    "Clinicians are interested in participating in Cabozantinib/Nivolumab trials.",
    "Clinicians are interested in the potential of Belzutifan in combination with TKIs.",
    "Clinicians are interested in the potential of Cabozantinib as a salvage therapy after Ipilimumab/Nivolumab.",
    "Clinicians are interested in treatment breaks and re-challenge with the same treatment for RCC patients.",
    "Clinicians are unsure about sequencing therapies with the availability of Cabozantinib/Nivolumab.",
    "Clinicians believe adjuvant therapy can improve outcomes for localized kidney cancer.",
    "Clinicians believe patients with sarcomatoid features may benefit from adjuvant therapy.",
    "Clinicians consider quality of life data when choosing treatments.",
    "Clinicians find conversations with patients about adjuvant therapy challenging.",
    "Clinicians have concerns about toxicity management with combination therapies like Lenvatinib/Pembrolizumab.",
    "Clinicians prefer Cabozantinib/Nivolumab combination due to better tolerability and efficacy.",
    "Clinicians use adjuvant Pembrolizumab in some patients.",
    "Collaboration between organizations and healthcare professionals is crucial for developing educational materials.",
    "Community pharmacists require support and education to better communicate with cancer patients.",
    "Concerns about toxicity and balancing efficacy with adverse events.",
    "Concerns about using CaboNivo in favorable IMDC mRCC patients.",
    "Concerns exist regarding the safety, tolerability, and side effect management of Belzutifan.",
    "Conferences and scientific meetings discuss the latest advancements in RCC research.",
    "Considerations for adjuvant treatment options and their potential benefits.",
    "Considerations for sequencing after first-line IO therapy.",
    "Desire for education and guidance on engaging with patient groups and advocates in research.",
    "Discussions around sequencing and positioning of Cabo+Nivo combination therapy.",
    "Discussions around the efficacy and toxicity management of IO-IO and IO-TKI combinations in first-line treatment of RCC.",
    "Dose intensity of pembrolizumab in combination therapy.",
    "Doubts about the efficacy of triplet therapy in certain patient subgroups.",
    "Effective management of patient compliance and adverse events is challenging.",
    "Emotional well-being and trust impact treatment adherence and outcomes.",
    "Emphasis on managing toxicities associated with IO therapies.",
    "Exploring novel combination therapies like TKI plus immunotherapy for second-line NSCLC treatment.",
    "Exploring the possibility of shorter IO treatment duration in combination therapies.",
    "Healthcare professionals are facing staffing crisis and resource constraints.",
    "Healthcare professionals are overwhelmed with increased workload and complex patient cases.",
    "Importance of considering patient characteristics and risk groups.",
    "Importance of identifying predictive biomarkers for response to IO and TKI therapies.",
    "Importance of providing flexible and multichannel engagement options for HCPs.",
    "Insights comparing Cabo+Nivo combination with other TKI+IO combinations like Len+Pembro.",
    "Insights discuss the prevalence and management of brain metastases in renal cell carcinoma patients.",
    "Insights discussing patient population and biomarker testing for NSCLC.",
    "Insights discussing the importance of patient-reported outcomes (PROs) and developing better tools for assessing them.",
    "Insights discussing the need for patient education materials for thyroid cancer treatments.",
    "Insights discussing the need for updated or refined risk stratification models for renal cell carcinoma patients.",
    "Insights discussing the potential challenges and considerations for implementing Cabo+Nivo combination.",
    "Insights discussing the presentation and analysis of clinical trial data for cabozantinib/nivolumab combination.",
    "Insights discussing the treatment patterns and lines of therapy for RCC patients.",
    "Insights highlight the lack of guidelines or consensus on screening for asymptomatic brain metastases.",
    "Insights highlighting the impact of NICE decisions on drug availability and funding.",
    "Insights highlighting the lack of treatment options and unmet needs for thyroid cancer patients.",
    "Insights highlighting the need for guidance on treatment strategies for favorable risk patients.",
    "Insights highlighting the preference and confidence of HCPs in using Cabo+Nivo combination.",
    "Insights indicate the need for better management and support for patients with brain metastases.",
    "Insights mention the timing and frequency of brain imaging for monitoring brain metastases.",
    "Insights mentioning early access programs for NSCLC treatments.",
    "Insights mentioning the use of Cabometyx and other TKIs for thyroid cancer treatment.",
    "Insights related to cabozantinib and atezolizumab combination therapy for NSCLC.",
    "Insights related to clinical trials for non-small cell lung cancer (NSCLC) treatment.",
    "Insights related to dosing strategies and dose optimization for Cabo+Nivo combination.",
    "Insights related to guidelines and treatment recommendations for thyroid cancer.",
    "Insights related to ongoing or upcoming clinical trials involving Cabo+Nivo combination.",
    "Insights related to patient education and involvement in treatment decisions.",
    "Insights related to understanding real-world evidence and treatment decision-making for cabozantinib/nivolumab combination in renal cell carcinoma.",
    "Insights related to understanding the use of cabozantinib/nivolumab combination in later lines of therapy.",
    "Lack of education and resources for managing toxicities of TKI+IO combinations.",
    "Lack of knowledge about ESMO and EAU recommendations for nccRCC management.",
    "Lack of understanding among non-consultant HCPs on how to collaborate with pharmaceutical companies.",
    "Microbiome and its role in immunotherapy response is an emerging area of interest.",
    "Multidisciplinary team approach for NSCLC patient management.",
    "Need for efficient TKI management and toxicity support.",
    "Need for materials and resources to discuss Ipsen's pipeline and early-stage research.",
    "Need for training and support for early-career HCPs on leading multidisciplinary team (MDT) meetings.",
    "Nurses seek education on treatment sequencing and adverse event management.",
    "Nutritional support for pancreatic cancer patients.",
    "Patient perspectives on treatment outcomes and toxicities.",
    "Pharmacists need assistance in aligning with approved treatments and managing patient education.",
    "Positive feedback and value perceived from interactive and engaging medical education sessions.",
    "Potential for rechallenge with IO therapy after a break.",
    "Preference for IO-IO combination in the first-line setting.",
    "Preference for PembroAxi over CaboNivo due to familiarity with toxicity management.",
    "Preference for alternative treatments over CaboNivo in favorable IMDC mRCC patients.",
    "Preference for double IO in unfavorable IMDC patients, and CaboNivo as an alternative.",
    "Preference for monotherapy over TKI+IO combinations.",
    "Questioning the optimal treatment sequence and subsequent therapies.",
    "Rapidly changing treatment landscape and healthcare staff turnover impact patient care.",
    "Rechallenge with immunotherapy agents is practiced in NSCLC.",
    "Reluctance to use pembrolizumab again due to severe side effects.",
    "Role of nephrectomy in metastatic RCC.",
    "Second-line treatment options for advanced non-small cell lung cancer (NSCLC) have limitations.",
    "Sharing best practices across regions can support patient outcomes and healthcare professionals during stressful times.",
    "Staffing crisis is impacting patient care and treatment management.",
    "Tazemetostat is being considered as a potential treatment option for bladder cancer.",
    "Tazemetostat is being evaluated in a clinical trial for sarcoma, and patient enrollment may be challenging.",
    "Tazemetostat is considered an efficacious and tolerable treatment option for follicular lymphoma patients in later lines of therapy.",
    "Tazemetostat may be combined with other novel therapies like bispecific antibodies for follicular lymphoma treatment.",
    "The 40mg dosing of cabozantinib in combination with nivolumab is beneficial for RCC patients with poor performance status.",
    "There is a lack of evidence or data supporting the use of cabozantinib for RCC patients with brain metastases.",
    "There is a lack of treatment options for follicular lymphoma patients in the UK, particularly in later lines.",
    "There is a need for more data and evidence to support treatment decisions for RCC patients with bone metastases.",
    "There is interest and excitement among HCPs regarding Belzutifan trials, but more data is needed.",
    "There is interest in exploring tazemetostat in combination with CAR T-cell therapy for follicular lymphoma.",
    "There is interest in exploring the potential of a triple combination of cabozantinib, nivolumab, and ipilimumab for RCC patients.",
    "Treatment approach after relapse following adjuvant pembrolizumab therapy.",
    "Treatment selection and sequencing considerations for combination therapies.",
    "Treatment sequencing and options after Cabo/Nivo combination therapy.",
    "Treatment strategies for different types of renal cell carcinoma (RCC).",
    "Unexplained phenomenon of adverse event resolution after treatment break.",
    "Use of TKI monotherapy in specific patient populations.",
]

allowed_nodes = []


examples = [
    {
        "text": (
            "Adam is a software engineer in Microsoft since 2009, "
            "and last year he got an award as the Best Talent"
        ),
        "head": "Adam",
        "head_type": "Person",
        "relation": "WORKS_FOR",
        "tail": "Microsoft",
        "tail_type": "Company",
    },
    {
        "text": (
            "Adam is a software engineer in Microsoft since 2009, "
            "and last year he got an award as the Best Talent"
        ),
        "head": "Adam",
        "head_type": "Person",
        "relation": "HAS_AWARD",
        "tail": "Best Talent",
        "tail_type": "Award",
    },
    {
        "text": (
            "Microsoft is a tech company that provide "
            "several products such as Microsoft Word"
        ),
        "head": "Microsoft Word",
        "head_type": "Product",
        "relation": "PRODUCED_BY",
        "tail": "Microsoft",
        "tail_type": "Company",
    },
    {
        "text": "Microsoft Word is a lightweight app that accessible offline",
        "head": "Microsoft Word",
        "head_type": "Product",
        "relation": "HAS_CHARACTERISTIC",
        "tail": "lightweight app",
        "tail_type": "Characteristic",
    },
    {
        "text": "Microsoft Word is a lightweight app that accessible offline",
        "head": "Microsoft Word",
        "head_type": "Product",
        "relation": "HAS_CHARACTERISTIC",
        "tail": "accessible offline",
        "tail_type": "Characteristic",
    },
]
